tokio 1.0
sile/bytecodec pull request #6
Opened 2021-03-18 10:32 UTC by koba-e964

This PR adds `tokio`-based future support. You can enable the functionality by adding `features = ["tokio-async"]` to the dependency.

Example of how to use: https://github.com/sile/fibers_http_server/compare/master...koba-e964:tmp/tokio-1.0

The newly added function `execute_io_poll` is called [here](https://github.com/sile/fibers_http_server/compare/master...koba-e964:tmp/tokio-1.0#diff-68923d8302dccbcf4197d9a4d936226739cb7348ad30f173f7de2f301c23b0afR176).

2021-03-19 10:01 UTC, koba-e964 commented
`execute_io_poll` now has a problem. As in [tokio's functions](https://github.com/tokio-rs/tokio/blob/tokio-util-0.6.0/tokio/src/io/util/read_to_end.rs#L44-L54), poll_xxx must be called in a loop repeatedly until `Poll::Pending` or `Poll::Ready(Ok(0))` is returned.
Converted this PR to a draft.

2021-04-01 11:43 UTC, koba-e964 commented
This PR is now ready for review.

2021-04-01 12:01 UTC, sile commented
Thanks! Let me review this PR this weekend.

2021-04-03 14:13 UTC, sile requested changes
Thank you for your PR.
I haven't confirmed this patch works as expected but it looks good.
I left minor comments so please take a look at them.

2021-04-03 14:13 UTC, sile commented on src/io_async.rs
> +            // rbuf 側と wbuf 側のどちらの準備ができても、この future は呼び起こされる。
Would you translate this comment into English?

2021-04-03 14:13 UTC, sile commented on src/io_async.rs
> +        // rbuf 側と wbuf 側のどちらも Poll::Pending を返す状態でないと、この future が呼び起こされる保証がない。
Ditto.

2021-04-03 14:13 UTC, sile commented on src/io_async.rs
> +use core::task::{Context, Poll as Poll03};
Why did you need `Poll as Poll03`?

2021-04-06 09:08 UTC, koba-e964 commented on src/io_async.rs
> +            // rbuf 側と wbuf 側のどちらの準備ができても、この future は呼び起こされる。
Somehow Japanese sentences remained...
I'll translate this.

2021-04-07 07:29 UTC, koba-e964 commented on src/io_async.rs
> +use core::task::{Context, Poll as Poll03};
I didn't need it here. Fixed.

2021-04-07 07:30 UTC, koba-e964 commented on src/io_async.rs
> +            // rbuf 側と wbuf 側のどちらの準備ができても、この future は呼び起こされる。
Fixed.

2021-04-07 07:30 UTC, koba-e964 commented on src/io_async.rs
> +        // rbuf 側と wbuf 側のどちらも Poll::Pending を返す状態でないと、この future が呼び起こされる保証がない。
Fixed.

2021-04-09 12:25 UTC, sile approved these changes
LGTM!

2021-04-09 12:25 UTC, merged

2021-04-09 12:51 UTC, sile commented
Just published v0.4.14